version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: ["./wait-for-it.sh", "database:5432", "--", "yarn", "run:server"]
    volumes:
      - /usr/src/app
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
    depends_on:
      - database
      
  storefront:
    build:
      context: .
      dockerfile: Dockerfile-storefront
      args:
        STOREFRONT_VERSION: 0.1.27
    ports:
      - 4000:4000
    environment:
      SERVER_API_HOST: https://pohs.cleopatra.quest
      SERVER_API_PORT: 443
      SERVER_API_PATH: shop-api
