version: "3"
services:
  storefront:
    build:
      context: .
      dockerfile: Dockerfile-storefront
      args:
        STOREFRONT_VERSION: 0.3.0
    ports:
      - 4000:4000
    environment:
      SERVER_API_HOST: https://pohs.cleopatra.quest
      SERVER_API_PORT: 443
      SERVER_API_PATH: shop-api
